exclude: ^(anshun/frontend/antlr/|tests/data/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
        exclude: keypair.json$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: keypair.json$

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
        args: ["--workspace"]
