exclude: ^(anshun/frontend/antlr/|tests/data/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
        exclude: keypair.json$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: keypair.json$

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--", "--allow", "clippy::result_large_err"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: (.json)$

  - repo: local
    hooks:
      - id: solana-key-check
        name: solana private key check
        entry: "\\[\\s*([0-9]{1,3}\\s*,\\s*){63}[0-9]{1,3}\\s*\\]"
        language: pygrep
        types: [text]
        exclude: ^target/deploy/(anchor_test|basic_4|counter)-keypair.json$
