name: ci

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: append path
        run: |
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo "$HOME/.avm/bin" >> $GITHUB_PATH

      - name: install rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

      - name: install solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          solana-install init 1.14.16

      - name: install anchor
        run: |
          cargo install --git https://github.com/project-serum/anchor avm --locked --force
          avm install 0.27.0
          avm use 0.27.0

      - name: run test on localnet
        run: |
          yarn
          solana-keygen new --no-bip39-passphrase
          anchor test --provider.cluster localnet
